In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('서울시CCTV설치운영현황(자치구)_년도별_210731기준.csv',encoding='cp949', skiprows=1)
df.drop([0],inplace=True)
df

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
1,종로구,"1,772",813,0,0,210,150,1,261,85,9,200,43
2,중 구,"2,333",16,114,87,77,236,240,372,386,155,361,289
3,용산구,"2,383",34,71,234,125,221,298,351,125,307,617,0
4,성동구,"3,602",448,125,212,105,339,310,874,390,262,461,76
5,광진구,"2,588",35,57,100,187,98,52,675,465,712,175,32
6,동대문구,"2,497","1,090",146,60,29,111,233,136,197,209,223,63
7,중랑구,"3,296",302,24,253,88,141,161,162,173,1049,939,4
8,성북구,"3,958",83,78,170,230,323,594,460,867,714,251,188
9,강북구,"2,462",0,0,24,65,105,243,6,392,1000,588,39
10,도봉구,"1,629",39,22,96,181,79,159,134,222,198,168,331
11,노원구,"2,415",0,97,193,77,516,331,175,216,320,386,104
12,은평구,"3,791",14,3,44,332,329,555,403,635,1057,288,131
13,서대문구,"2,940",730,253,155,108,137,223,356,237,343,397,1
14,마포구,"2,421",58,93,77,61,162,454,359,343,494,300,20
15,양천구,"3,312","1,413",167,181,143,180,350,139,140,274,325,0
16,강서구,"2,560",55,129,106,213,188,168,506,259,457,356,123
17,구로구,"4,075",852,216,349,187,268,326,540,488,434,415,0
18,금천구,"2,374",0,0,178,80,361,133,196,540,369,508,9
19,영등포구,"3,778",572,136,238,123,209,248,311,658,65,"1,213",5
20,동작구,"2,297",41,24,25,503,128,253,271,300,322,419,11
21,관악구,"4,942",428,205,291,513,529,621,687,663,640,331,34
22,서초구,"3,704",116,75,94,71,563,516,1060,428,358,420,3
23,강남구,"6,502",124,77,75,597,840,1310,999,748,789,942,1
24,송파구,"2,854",72,61,86,85,215,148,241,542,1068,235,101
25,강동구,"2,547",332,27,163,49,154,202,273,377,356,614,0

In [20]:
people = pd.read_excel('Report (2).xls',usecols='A,B,D,G,J')
people

       기간  자치구        인구      인구.3    인구.6
0      기간  자치구        합계       한국인   등록외국인
1      기간  자치구         계         계       계
2    2012   합계  10442426  10195318  247108
3    2012  종로구    173148    165207    7941
4    2012   중구    140807    133360    7447
..    ...  ...       ...       ...     ...
231  2020  관악구    509803    495060   14743
232  2020  서초구    429025    425126    3899
233  2020  강남구    544055    539231    4824
234  2020  송파구    673926    667960    5966
235  2020  강동구    463998    459970    4028

[236 rows x 5 columns]

In [ ]:
people.rename(columns={people.columns[0]:'구별',
                          people.columns[1]:'인구수',
                          people.columns[2]:'한국인',
                          people.columns[3]:'외국인',
                          people.columns[4]:'고령자'
                         }, inplace=True)
people.head()